### ISSUE TITLE
Postgres API missing functions

### ISSUE THREAD

**Issue by kongeor** [joy-framework/db#4]
Hello,

thank you for your amazing work on joy.

The pg API seems to have much less functions comparing to the sqlite one (update is missing for example). 

I played with it a bit and adding the missing things doesn't look that hard so I can do that.

**Comment by swlkr** [comment]
Hey I added `update`, `update-all`, `delete` and `delete-all` to the postgres side of things

https://github.com/joy-framework/db/commit/ce2dac21aeffab8a27469b5bf072ef6ea13c179c
https://github.com/joy-framework/db/commit/d979aeb9dab867dc8d8fce0193314405beedf446
